# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'realtime_crowd_insights_sb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for realtime_crowd_insights
  pod 'SwiftyJSON', '~> 4.0'

end
